version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/FantomasVs.VS2019"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "Fantomas.Client"
- package-ecosystem: nuget
  directory: "/src/FantomasVs.VS2022"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "Fantomas.Client"
